SELECT A.FLAVOR
FROM FIRST_HALF A
    INNER JOIN (SELECT FLAVOR, sum(TOTAL_ORDER) JULY_TOTAL_ORDER
                FROM JULY
                GROUP BY FLAVOR) B
        ON A.FLAVOR = B.FLAVOR
ORDER BY TOTAL_ORDER + JULY_TOTAL_ORDER DESC
LIMIT 3;
