-- 코드를 입력하세요
SELECT A.TITLE , A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS,
DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
from USED_GOODS_BOARD A INNER JOIN USED_GOODS_REPLY  B
on A.BOARD_ID = B.BOARD_ID
where A.CREATED_DATE like '%2022-10%'
order by CREATED_DATE asc, TITLE asc