-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME,DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
from BOOK A inner join AUTHOR B on A.AUTHOR_ID = B.AUTHOR_ID
where CATEGORY = '경제'
order by PUBLISHED_DATE